[2023-08-16T23:27:34.762+0300] {processor.py:157} INFO - Started process (PID=192901) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:27:34.765+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:27:34.768+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:27:34.767+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:27:34.786+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:27:34.782+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:27:34.788+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:27:35.383+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.635 seconds
[2023-08-16T23:28:38.480+0300] {processor.py:157} INFO - Started process (PID=193558) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:28:38.498+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:28:38.501+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:28:38.500+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:28:38.521+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:28:38.517+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:28:38.523+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:28:38.665+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.200 seconds
[2023-08-16T23:29:09.045+0300] {processor.py:157} INFO - Started process (PID=193990) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:29:09.065+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:29:09.068+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:29:09.067+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:29:09.094+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:29:09.089+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:29:09.095+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:29:09.234+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.230 seconds
[2023-08-16T23:29:41.406+0300] {processor.py:157} INFO - Started process (PID=194621) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:29:41.420+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:29:41.423+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:29:41.422+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:29:41.442+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:29:41.439+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:29:41.443+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:29:41.591+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.198 seconds
[2023-08-16T23:30:12.727+0300] {processor.py:157} INFO - Started process (PID=195251) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:30:12.746+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:30:12.749+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:30:12.748+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:30:12.761+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:30:12.758+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:30:12.763+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:30:12.905+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.191 seconds
[2023-08-16T23:30:43.751+0300] {processor.py:157} INFO - Started process (PID=195907) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:30:43.755+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:30:43.758+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:30:43.757+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:30:43.778+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:30:43.773+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:30:43.780+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:30:44.182+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.450 seconds
[2023-08-16T23:31:15.927+0300] {processor.py:157} INFO - Started process (PID=196353) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:31:15.937+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:31:15.941+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:31:15.940+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:31:15.964+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:31:15.961+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:31:15.972+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:31:16.183+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.279 seconds
[2023-08-16T23:31:46.628+0300] {processor.py:157} INFO - Started process (PID=196746) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:31:46.632+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:31:46.637+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:31:46.635+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:31:46.655+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:31:46.650+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:31:46.657+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:31:46.893+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.285 seconds
[2023-08-16T23:32:17.115+0300] {processor.py:157} INFO - Started process (PID=197296) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:32:17.128+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:32:17.132+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:32:17.130+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:32:17.174+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:32:17.154+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:32:17.185+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:32:17.562+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.479 seconds
[2023-08-16T23:32:48.383+0300] {processor.py:157} INFO - Started process (PID=197872) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:32:48.405+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:32:48.408+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:32:48.407+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:32:48.419+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:32:48.416+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:32:48.420+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:32:48.616+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.257 seconds
[2023-08-16T23:33:18.748+0300] {processor.py:157} INFO - Started process (PID=198452) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:33:18.763+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:33:18.766+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:33:18.765+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:33:18.807+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:33:18.785+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:33:18.815+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:33:19.256+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.522 seconds
[2023-08-16T23:33:50.221+0300] {processor.py:157} INFO - Started process (PID=199050) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:33:50.224+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:33:50.227+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:33:50.226+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:33:50.264+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:33:50.253+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:33:50.265+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:33:50.693+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.507 seconds
[2023-08-16T23:34:21.257+0300] {processor.py:157} INFO - Started process (PID=199472) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:34:21.259+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:34:21.262+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:34:21.261+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:34:21.275+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:34:21.272+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:34:21.277+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:34:21.434+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.197 seconds
[2023-08-16T23:34:52.309+0300] {processor.py:157} INFO - Started process (PID=199869) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:34:52.333+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:34:52.336+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:34:52.335+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:34:52.362+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:34:52.359+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:34:52.363+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:34:52.669+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.399 seconds
[2023-08-16T23:35:23.974+0300] {processor.py:157} INFO - Started process (PID=200440) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:35:24.015+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:35:24.018+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:35:24.017+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:35:24.042+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:35:24.039+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:35:24.044+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:35:24.188+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.287 seconds
[2023-08-16T23:35:55.527+0300] {processor.py:157} INFO - Started process (PID=200872) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:35:55.531+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:35:55.534+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:35:55.533+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:35:55.561+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:35:55.553+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:35:55.563+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:35:55.834+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.326 seconds
[2023-08-16T23:36:26.445+0300] {processor.py:157} INFO - Started process (PID=201473) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:36:26.468+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:36:26.471+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:36:26.470+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:36:26.537+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:36:26.523+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:36:26.538+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:36:26.713+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.301 seconds
[2023-08-16T23:36:56.840+0300] {processor.py:157} INFO - Started process (PID=202031) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:36:56.858+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:36:56.861+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:36:56.860+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:36:56.881+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:36:56.874+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:36:56.882+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:36:57.257+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.431 seconds
[2023-08-16T23:37:29.314+0300] {processor.py:157} INFO - Started process (PID=202447) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:37:29.319+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:37:29.321+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:37:29.321+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:37:29.371+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:37:29.346+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:37:29.373+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:37:29.674+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.401 seconds
[2023-08-16T23:38:00.359+0300] {processor.py:157} INFO - Started process (PID=202875) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:38:00.377+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:38:00.380+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:38:00.379+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:38:00.405+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:38:00.401+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:38:00.406+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:38:00.567+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.224 seconds
[2023-08-16T23:38:31.796+0300] {processor.py:157} INFO - Started process (PID=203436) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:38:31.821+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:38:31.827+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:38:31.825+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:38:31.849+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:38:31.841+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:38:31.850+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:38:32.081+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.310 seconds
[2023-08-16T23:39:02.501+0300] {processor.py:157} INFO - Started process (PID=203894) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:39:02.522+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:39:02.524+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:39:02.523+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:39:02.542+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:39:02.539+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:39:02.545+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:39:02.745+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.262 seconds
[2023-08-16T23:39:34.695+0300] {processor.py:157} INFO - Started process (PID=204511) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:39:34.699+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:39:34.703+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:39:34.701+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:39:34.712+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:39:34.710+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:39:34.713+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:39:34.816+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.131 seconds
[2023-08-16T23:40:07.049+0300] {processor.py:157} INFO - Started process (PID=205127) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:40:07.064+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:40:07.067+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:40:07.066+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:40:07.084+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:40:07.080+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:40:07.085+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:40:07.387+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.350 seconds
[2023-08-16T23:40:38.431+0300] {processor.py:157} INFO - Started process (PID=205542) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:40:38.460+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:40:38.464+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:40:38.463+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:40:38.482+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:40:38.478+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:40:38.485+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:40:38.706+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.292 seconds
[2023-08-16T23:41:09.535+0300] {processor.py:157} INFO - Started process (PID=206139) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:41:09.554+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:41:09.557+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:41:09.556+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:41:09.590+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:41:09.572+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:41:09.591+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:41:09.975+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.465 seconds
[2023-08-16T23:41:42.143+0300] {processor.py:157} INFO - Started process (PID=206541) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:41:42.152+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:41:42.155+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:41:42.154+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:41:42.201+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:41:42.189+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:41:42.204+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:41:42.463+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.356 seconds
[2023-08-16T23:42:13.607+0300] {processor.py:157} INFO - Started process (PID=207139) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:42:13.620+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:42:13.623+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:42:13.622+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:42:13.657+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:42:13.640+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:42:13.658+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:42:13.928+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.336 seconds
[2023-08-16T23:42:44.343+0300] {processor.py:157} INFO - Started process (PID=207528) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:42:44.394+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:42:44.412+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:42:44.403+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:42:44.473+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:42:44.452+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:42:44.475+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:42:44.689+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.397 seconds
[2023-08-16T23:43:15.563+0300] {processor.py:157} INFO - Started process (PID=208094) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:43:15.583+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:43:15.587+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:43:15.586+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:43:15.600+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:43:15.597+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:43:15.602+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:43:15.729+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.209 seconds
[2023-08-16T23:43:46.384+0300] {processor.py:157} INFO - Started process (PID=208494) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:43:46.396+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:43:46.399+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:43:46.398+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:43:46.434+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:43:46.422+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:43:46.435+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:43:46.954+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.602 seconds
[2023-08-16T23:44:18.778+0300] {processor.py:157} INFO - Started process (PID=209074) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:44:18.816+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:44:18.820+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:44:18.819+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:44:18.849+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:44:18.843+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:44:18.850+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:44:19.295+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.561 seconds
[2023-08-16T23:44:50.314+0300] {processor.py:157} INFO - Started process (PID=209460) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:44:50.325+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:44:50.333+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:44:50.330+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:44:50.380+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:44:50.365+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:44:50.381+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:44:50.729+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.492 seconds
[2023-08-16T23:45:20.987+0300] {processor.py:157} INFO - Started process (PID=210043) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:45:21.004+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:45:21.009+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:45:21.008+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:45:21.052+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:45:21.049+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:45:21.061+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:45:21.190+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.245 seconds
[2023-08-16T23:45:52.256+0300] {processor.py:157} INFO - Started process (PID=210433) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:45:52.261+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:45:52.266+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:45:52.264+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:45:52.292+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:45:52.284+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:45:52.295+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:45:52.546+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.309 seconds
[2023-08-16T23:46:22.997+0300] {processor.py:157} INFO - Started process (PID=211010) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:46:23.018+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:46:23.046+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:46:23.030+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:46:23.092+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:46:23.088+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:46:23.101+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:46:23.651+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.680 seconds
[2023-08-16T23:46:53.883+0300] {processor.py:157} INFO - Started process (PID=211388) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:46:53.898+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:46:53.907+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:46:53.906+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:46:53.979+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:46:53.958+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:46:53.980+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:46:54.479+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.651 seconds
[2023-08-16T23:47:26.186+0300] {processor.py:157} INFO - Started process (PID=211977) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:47:26.207+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:47:26.214+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:47:26.213+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:47:26.234+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:47:26.230+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:47:26.235+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:47:26.514+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.361 seconds
[2023-08-16T23:47:57.106+0300] {processor.py:157} INFO - Started process (PID=212404) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:47:57.130+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:47:57.135+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:47:57.134+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:47:57.174+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:47:57.167+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:47:57.176+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:47:57.474+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.399 seconds
[2023-08-16T23:48:28.889+0300] {processor.py:157} INFO - Started process (PID=212980) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:48:28.910+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:48:28.918+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:48:28.915+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:48:28.940+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:48:28.937+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:48:28.941+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:48:29.457+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.595 seconds
[2023-08-16T23:49:00.279+0300] {processor.py:157} INFO - Started process (PID=213390) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:49:00.312+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:49:00.321+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:49:00.313+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:49:00.402+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:49:00.390+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:49:00.404+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:49:00.696+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.477 seconds
[2023-08-16T23:49:31.191+0300] {processor.py:157} INFO - Started process (PID=213976) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:49:31.201+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:49:31.205+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:49:31.204+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:49:31.224+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:49:31.220+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:49:31.226+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:49:31.485+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.311 seconds
[2023-08-16T23:50:01.775+0300] {processor.py:157} INFO - Started process (PID=214539) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:50:01.788+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:50:01.791+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:50:01.790+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:50:01.825+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:50:01.821+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:50:01.832+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:50:02.101+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.342 seconds
[2023-08-16T23:50:32.492+0300] {processor.py:157} INFO - Started process (PID=214915) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:50:32.512+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:50:32.523+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:50:32.517+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:50:32.541+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:50:32.537+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:50:32.545+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:50:32.709+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.294 seconds
[2023-08-16T23:51:03.560+0300] {processor.py:157} INFO - Started process (PID=215320) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:51:03.586+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:51:03.589+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:51:03.588+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:51:03.612+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:51:03.608+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:51:03.613+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:51:03.763+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.218 seconds
[2023-08-16T23:51:33.983+0300] {processor.py:157} INFO - Started process (PID=215901) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:51:33.997+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:51:34.000+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:51:33.999+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:51:34.031+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:51:34.021+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:51:34.033+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:51:34.246+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.279 seconds
[2023-08-16T23:52:04.859+0300] {processor.py:157} INFO - Started process (PID=216302) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:52:04.862+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:52:04.881+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:52:04.865+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:52:04.903+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:52:04.899+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:52:04.905+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:52:05.333+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.491 seconds
[2023-08-16T23:52:35.514+0300] {processor.py:157} INFO - Started process (PID=216874) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:52:35.533+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:52:35.536+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:52:35.535+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:52:35.551+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:52:35.547+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:52:35.552+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:52:35.696+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.200 seconds
[2023-08-16T23:53:06.698+0300] {processor.py:157} INFO - Started process (PID=217430) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:53:06.711+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:53:06.716+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:53:06.714+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:53:06.735+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:53:06.730+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:53:06.737+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:53:06.931+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.249 seconds
[2023-08-16T23:53:38.162+0300] {processor.py:157} INFO - Started process (PID=217865) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:53:38.176+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:53:38.180+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:53:38.179+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:53:38.218+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:53:38.207+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:53:38.220+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:53:38.417+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.295 seconds
[2023-08-16T23:54:09.144+0300] {processor.py:157} INFO - Started process (PID=218277) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:54:09.179+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:54:09.182+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:54:09.181+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:54:09.229+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:54:09.213+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:54:09.230+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:54:09.512+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.407 seconds
[2023-08-16T23:54:40.265+0300] {processor.py:157} INFO - Started process (PID=218841) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:54:40.280+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:54:40.284+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:54:40.283+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:54:40.298+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:54:40.294+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:54:40.300+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:54:40.478+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.228 seconds
[2023-08-16T23:55:12.479+0300] {processor.py:157} INFO - Started process (PID=219351) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:55:12.501+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:55:12.505+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:55:12.503+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:55:12.523+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:55:12.519+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:55:12.525+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:55:12.874+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.411 seconds
[2023-08-16T23:55:43.811+0300] {processor.py:157} INFO - Started process (PID=219869) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:55:43.828+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:55:43.832+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:55:43.831+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:55:43.848+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:55:43.844+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:55:43.850+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:55:43.984+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.190 seconds
[2023-08-16T23:56:14.273+0300] {processor.py:157} INFO - Started process (PID=220434) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:56:14.282+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:56:14.284+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:56:14.284+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:56:14.298+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:56:14.295+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:56:14.299+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:56:14.509+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.260 seconds
[2023-08-16T23:56:46.002+0300] {processor.py:157} INFO - Started process (PID=220878) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:56:46.015+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:56:46.018+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:56:46.017+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:56:46.115+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:56:46.060+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:56:46.126+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:56:46.467+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.529 seconds
[2023-08-16T23:57:16.685+0300] {processor.py:157} INFO - Started process (PID=221373) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:57:16.828+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:57:16.834+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:57:16.832+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:57:16.854+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:57:16.850+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:57:16.856+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:57:17.028+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.363 seconds
[2023-08-16T23:57:47.868+0300] {processor.py:157} INFO - Started process (PID=221857) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:57:47.872+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:57:47.875+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:57:47.874+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:57:47.890+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:57:47.886+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:57:47.891+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:57:48.221+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.369 seconds
[2023-08-16T23:58:18.428+0300] {processor.py:157} INFO - Started process (PID=222466) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:58:18.433+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:58:18.438+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:58:18.436+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:58:18.462+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:58:18.457+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:58:18.464+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:58:18.641+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.239 seconds
[2023-08-16T23:58:53.842+0300] {processor.py:157} INFO - Started process (PID=223094) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:58:53.878+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:58:53.882+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:58:53.880+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:58:53.914+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:58:53.911+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:58:53.915+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:58:54.296+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.492 seconds
[2023-08-16T23:59:24.918+0300] {processor.py:157} INFO - Started process (PID=223508) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:59:24.930+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:59:24.934+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:59:24.933+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:59:25.027+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:59:25.012+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:59:25.029+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:59:25.401+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.539 seconds
[2023-08-16T23:59:58.101+0300] {processor.py:157} INFO - Started process (PID=223953) to work on /home/ylan/airflow/dags/main.py
[2023-08-16T23:59:58.141+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-16T23:59:58.145+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:59:58.144+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-16T23:59:58.171+0300] {logging_mixin.py:150} INFO - [2023-08-16T23:59:58.167+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-16T23:59:58.172+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-16T23:59:58.681+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.601 seconds
[2023-08-17T00:00:30.860+0300] {processor.py:157} INFO - Started process (PID=224410) to work on /home/ylan/airflow/dags/main.py
[2023-08-17T00:00:30.897+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-17T00:00:30.901+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:00:30.899+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-17T00:00:30.934+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:00:30.929+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-17T00:00:30.939+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-17T00:00:31.226+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.398 seconds
[2023-08-17T00:01:05.251+0300] {processor.py:157} INFO - Started process (PID=224987) to work on /home/ylan/airflow/dags/main.py
[2023-08-17T00:01:05.261+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-17T00:01:05.266+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:01:05.265+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-17T00:01:05.312+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:01:05.293+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-17T00:01:05.316+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-17T00:01:05.550+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.322 seconds
[2023-08-17T00:01:43.548+0300] {processor.py:157} INFO - Started process (PID=225587) to work on /home/ylan/airflow/dags/main.py
[2023-08-17T00:01:43.563+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-17T00:01:43.566+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:01:43.565+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-17T00:01:43.655+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:01:43.622+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-17T00:01:43.656+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-17T00:01:44.041+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.565 seconds
[2023-08-17T00:02:15.096+0300] {processor.py:157} INFO - Started process (PID=226169) to work on /home/ylan/airflow/dags/main.py
[2023-08-17T00:02:15.106+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-17T00:02:15.110+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:02:15.108+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-17T00:02:15.153+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:02:15.149+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-17T00:02:15.166+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-17T00:02:15.393+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.317 seconds
[2023-08-17T00:02:58.188+0300] {processor.py:157} INFO - Started process (PID=226662) to work on /home/ylan/airflow/dags/main.py
[2023-08-17T00:02:58.204+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-17T00:02:58.207+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:02:58.206+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-17T00:02:58.228+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:02:58.225+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-17T00:02:58.230+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-17T00:02:58.551+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.398 seconds
[2023-08-17T00:03:31.673+0300] {processor.py:157} INFO - Started process (PID=227068) to work on /home/ylan/airflow/dags/main.py
[2023-08-17T00:03:31.715+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-17T00:03:31.723+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:03:31.722+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-17T00:03:31.757+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:03:31.753+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-17T00:03:31.759+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-17T00:03:32.016+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.375 seconds
[2023-08-17T00:04:02.485+0300] {processor.py:157} INFO - Started process (PID=227504) to work on /home/ylan/airflow/dags/main.py
[2023-08-17T00:04:02.489+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-17T00:04:02.501+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:04:02.500+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-17T00:04:02.532+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:04:02.528+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-17T00:04:02.534+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-17T00:04:02.660+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.190 seconds
[2023-08-17T00:04:34.880+0300] {processor.py:157} INFO - Started process (PID=228079) to work on /home/ylan/airflow/dags/main.py
[2023-08-17T00:04:34.895+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-17T00:04:34.898+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:04:34.897+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-17T00:04:34.957+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:04:34.933+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-17T00:04:34.966+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-17T00:04:35.342+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.538 seconds
[2023-08-17T00:05:06.054+0300] {processor.py:157} INFO - Started process (PID=228531) to work on /home/ylan/airflow/dags/main.py
[2023-08-17T00:05:06.216+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-17T00:05:06.219+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:05:06.218+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-17T00:05:06.231+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:05:06.228+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-17T00:05:06.233+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-17T00:05:06.601+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.568 seconds
[2023-08-17T00:05:36.768+0300] {processor.py:157} INFO - Started process (PID=229221) to work on /home/ylan/airflow/dags/main.py
[2023-08-17T00:05:36.860+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-17T00:05:36.864+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:05:36.863+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-17T00:05:36.878+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:05:36.875+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-17T00:05:36.879+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-17T00:05:37.242+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.488 seconds
[2023-08-17T00:06:09.765+0300] {processor.py:157} INFO - Started process (PID=229653) to work on /home/ylan/airflow/dags/main.py
[2023-08-17T00:06:09.773+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-17T00:06:09.776+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:06:09.775+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-17T00:06:09.796+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:06:09.793+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-17T00:06:09.798+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-17T00:06:09.993+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.251 seconds
[2023-08-17T00:06:17.303+0300] {processor.py:157} INFO - Started process (PID=229758) to work on /home/ylan/airflow/dags/main.py
[2023-08-17T00:06:17.349+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-17T00:06:17.376+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:06:17.367+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-17T00:06:17.468+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:06:17.461+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-17T00:06:17.478+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-17T00:06:17.982+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.796 seconds
[2023-08-17T00:06:48.968+0300] {processor.py:157} INFO - Started process (PID=230149) to work on /home/ylan/airflow/dags/main.py
[2023-08-17T00:06:48.970+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-17T00:06:48.974+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:06:48.973+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-17T00:06:48.992+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:06:48.989+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-17T00:06:48.994+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-17T00:06:49.299+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.346 seconds
[2023-08-17T00:08:21.588+0300] {processor.py:157} INFO - Started process (PID=231803) to work on /home/ylan/airflow/dags/main.py
[2023-08-17T00:08:21.625+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-17T00:08:21.628+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:08:21.627+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-17T00:08:21.688+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:08:21.678+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-17T00:08:21.753+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-17T00:08:22.465+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 1.012 seconds
[2023-08-17T00:08:53.004+0300] {processor.py:157} INFO - Started process (PID=232221) to work on /home/ylan/airflow/dags/main.py
[2023-08-17T00:08:53.042+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-17T00:08:53.045+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:08:53.044+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-17T00:08:53.094+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:08:53.079+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-17T00:08:53.095+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-17T00:08:53.346+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.434 seconds
[2023-08-17T00:09:26.649+0300] {processor.py:157} INFO - Started process (PID=232714) to work on /home/ylan/airflow/dags/main.py
[2023-08-17T00:09:26.655+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-17T00:09:26.662+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:09:26.661+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-17T00:09:26.686+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:09:26.682+0300] {dagbag.py:350} ERROR - Failed to import: /home/ylan/airflow/dags/main.py
Traceback (most recent call last):
  File "/home/ylan/airflow/venv/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ylan/airflow/dags/main.py", line 9, in <module>
    from dags.scripts.to_s3 import upload_to_s3
ModuleNotFoundError: No module named 'dags'
[2023-08-17T00:09:26.687+0300] {processor.py:838} WARNING - No viable dags retrieved from /home/ylan/airflow/dags/main.py
[2023-08-17T00:09:26.825+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.220 seconds
[2023-08-17T00:09:48.391+0300] {processor.py:157} INFO - Started process (PID=232948) to work on /home/ylan/airflow/dags/main.py
[2023-08-17T00:09:48.429+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-17T00:09:48.473+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:09:48.454+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-17T00:09:50.942+0300] {processor.py:836} INFO - DAG(s) dict_keys(['dag_data_lake']) retrieved from /home/ylan/airflow/dags/main.py
[2023-08-17T00:09:53.271+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:09:53.271+0300] {dag.py:2742} INFO - Sync 1 DAGs
[2023-08-17T00:09:53.508+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:09:53.500+0300] {dag.py:3504} INFO - Setting next_dagrun for dag_data_lake to 2023-08-16T20:00:00+00:00, run_after=2023-08-16T21:00:00+00:00
[2023-08-17T00:09:54.713+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 6.446 seconds
[2023-08-17T00:10:27.448+0300] {processor.py:157} INFO - Started process (PID=233466) to work on /home/ylan/airflow/dags/main.py
[2023-08-17T00:10:27.552+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-17T00:10:27.555+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:10:27.554+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-17T00:10:28.433+0300] {processor.py:836} INFO - DAG(s) dict_keys(['dag_data_lake']) retrieved from /home/ylan/airflow/dags/main.py
[2023-08-17T00:10:28.855+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:10:28.853+0300] {dag.py:2742} INFO - Sync 1 DAGs
[2023-08-17T00:10:29.686+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:10:29.686+0300] {dag.py:3504} INFO - Setting next_dagrun for dag_data_lake to 2023-08-16T21:00:00+00:00, run_after=2023-08-16T22:00:00+00:00
[2023-08-17T00:10:29.952+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 2.540 seconds
[2023-08-17T00:11:02.639+0300] {processor.py:157} INFO - Started process (PID=234069) to work on /home/ylan/airflow/dags/main.py
[2023-08-17T00:11:02.645+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-17T00:11:02.653+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:11:02.651+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-17T00:11:04.431+0300] {processor.py:836} INFO - DAG(s) dict_keys(['dag_data_lake']) retrieved from /home/ylan/airflow/dags/main.py
[2023-08-17T00:11:04.746+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:11:04.746+0300] {dag.py:2742} INFO - Sync 1 DAGs
[2023-08-17T00:11:04.937+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:11:04.937+0300] {dag.py:3504} INFO - Setting next_dagrun for dag_data_lake to 2023-08-16T21:00:00+00:00, run_after=2023-08-16T22:00:00+00:00
[2023-08-17T00:11:05.241+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 2.618 seconds
[2023-08-17T00:11:36.320+0300] {processor.py:157} INFO - Started process (PID=234700) to work on /home/ylan/airflow/dags/main.py
[2023-08-17T00:11:36.326+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-17T00:11:36.329+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:11:36.328+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-17T00:11:36.789+0300] {processor.py:836} INFO - DAG(s) dict_keys(['dag_data_lake']) retrieved from /home/ylan/airflow/dags/main.py
[2023-08-17T00:11:37.010+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:11:37.009+0300] {dag.py:2742} INFO - Sync 1 DAGs
[2023-08-17T00:11:37.242+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:11:37.242+0300] {dag.py:3504} INFO - Setting next_dagrun for dag_data_lake to 2023-08-16T21:00:00+00:00, run_after=2023-08-16T22:00:00+00:00
[2023-08-17T00:11:37.385+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 1.082 seconds
[2023-08-17T00:12:09.179+0300] {processor.py:157} INFO - Started process (PID=235298) to work on /home/ylan/airflow/dags/main.py
[2023-08-17T00:12:09.203+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-17T00:12:09.206+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:12:09.205+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-17T00:12:09.696+0300] {processor.py:836} INFO - DAG(s) dict_keys(['dag_data_lake']) retrieved from /home/ylan/airflow/dags/main.py
[2023-08-17T00:12:09.890+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:12:09.889+0300] {dag.py:2742} INFO - Sync 1 DAGs
[2023-08-17T00:12:10.122+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:12:10.109+0300] {dag.py:3504} INFO - Setting next_dagrun for dag_data_lake to 2023-08-16T21:00:00+00:00, run_after=2023-08-16T22:00:00+00:00
[2023-08-17T00:12:10.229+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 1.075 seconds
[2023-08-17T00:12:43.799+0300] {processor.py:157} INFO - Started process (PID=235779) to work on /home/ylan/airflow/dags/main.py
[2023-08-17T00:12:43.865+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-17T00:12:43.902+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:12:43.867+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-17T00:12:44.479+0300] {processor.py:836} INFO - DAG(s) dict_keys(['dag_data_lake']) retrieved from /home/ylan/airflow/dags/main.py
[2023-08-17T00:12:44.621+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:12:44.620+0300] {dag.py:2742} INFO - Sync 1 DAGs
[2023-08-17T00:12:44.850+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:12:44.843+0300] {dag.py:3504} INFO - Setting next_dagrun for dag_data_lake to 2023-08-16T21:00:00+00:00, run_after=2023-08-16T22:00:00+00:00
[2023-08-17T00:12:44.985+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 1.235 seconds
[2023-08-17T00:13:16.195+0300] {processor.py:157} INFO - Started process (PID=236242) to work on /home/ylan/airflow/dags/main.py
[2023-08-17T00:13:16.221+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-17T00:13:16.224+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:13:16.223+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-17T00:13:18.418+0300] {processor.py:836} INFO - DAG(s) dict_keys(['dag_data_lake']) retrieved from /home/ylan/airflow/dags/main.py
[2023-08-17T00:13:19.350+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:13:19.349+0300] {dag.py:2742} INFO - Sync 1 DAGs
[2023-08-17T00:13:20.311+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:13:20.311+0300] {dag.py:3504} INFO - Setting next_dagrun for dag_data_lake to 2023-08-16T21:00:00+00:00, run_after=2023-08-16T22:00:00+00:00
[2023-08-17T00:13:20.983+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 4.844 seconds
[2023-08-17T00:13:52.038+0300] {processor.py:157} INFO - Started process (PID=236731) to work on /home/ylan/airflow/dags/main.py
[2023-08-17T00:13:52.095+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-17T00:13:52.098+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:13:52.097+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-17T00:13:52.481+0300] {processor.py:836} INFO - DAG(s) dict_keys(['dag_data_lake']) retrieved from /home/ylan/airflow/dags/main.py
[2023-08-17T00:13:52.706+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:13:52.705+0300] {dag.py:2742} INFO - Sync 1 DAGs
[2023-08-17T00:13:52.873+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:13:52.873+0300] {dag.py:3504} INFO - Setting next_dagrun for dag_data_lake to 2023-08-16T21:00:00+00:00, run_after=2023-08-16T22:00:00+00:00
[2023-08-17T00:13:52.990+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 0.971 seconds
[2023-08-17T00:14:26.807+0300] {processor.py:157} INFO - Started process (PID=237378) to work on /home/ylan/airflow/dags/main.py
[2023-08-17T00:14:26.819+0300] {processor.py:826} INFO - Processing file /home/ylan/airflow/dags/main.py for tasks to queue
[2023-08-17T00:14:26.822+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:14:26.821+0300] {dagbag.py:541} INFO - Filling up the DagBag from /home/ylan/airflow/dags/main.py
[2023-08-17T00:14:27.642+0300] {processor.py:836} INFO - DAG(s) dict_keys(['dag_data_lake']) retrieved from /home/ylan/airflow/dags/main.py
[2023-08-17T00:14:28.351+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:14:28.350+0300] {dag.py:2742} INFO - Sync 1 DAGs
[2023-08-17T00:14:29.511+0300] {logging_mixin.py:150} INFO - [2023-08-17T00:14:29.511+0300] {dag.py:3504} INFO - Setting next_dagrun for dag_data_lake to 2023-08-16T21:00:00+00:00, run_after=2023-08-16T22:00:00+00:00
[2023-08-17T00:14:30.093+0300] {processor.py:179} INFO - Processing /home/ylan/airflow/dags/main.py took 3.326 seconds
