[2023-08-15T21:26:16.646+0300] {processor.py:157} INFO - Started process (PID=214944) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:26:16.649+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:26:16.652+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:26:16.651+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:26:16.699+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:26:16.684+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:26:16.700+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:26:16.699+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:26:16.700+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:26:16.749+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.126 seconds
[2023-08-15T21:29:36.148+0300] {processor.py:157} INFO - Started process (PID=217449) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:29:36.169+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:29:36.172+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:29:36.170+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:29:36.188+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:29:36.185+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:29:36.189+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:29:36.189+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:29:36.191+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:29:36.242+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.108 seconds
[2023-08-15T21:47:41.338+0300] {processor.py:157} INFO - Started process (PID=233839) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:47:41.374+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:47:41.376+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:47:41.375+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:47:41.387+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:47:41.385+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:47:41.388+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:47:41.388+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:47:41.389+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:47:41.477+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.153 seconds
[2023-08-15T21:48:12.617+0300] {processor.py:157} INFO - Started process (PID=234235) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:48:12.619+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:48:12.622+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:48:12.621+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:48:12.636+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:48:12.632+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:48:12.637+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:48:12.636+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:48:12.638+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:48:12.731+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.130 seconds
[2023-08-15T21:48:44.313+0300] {processor.py:157} INFO - Started process (PID=234857) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:48:44.329+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:48:44.331+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:48:44.330+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:48:44.385+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:48:44.382+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:48:44.385+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:48:44.385+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:48:44.388+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:48:44.700+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.425 seconds
[2023-08-15T21:49:23.542+0300] {processor.py:157} INFO - Started process (PID=235505) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:49:23.545+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:49:23.547+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:49:23.546+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:49:23.558+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:49:23.556+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:49:23.559+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:49:23.558+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:49:23.559+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:49:23.636+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.104 seconds
[2023-08-15T21:49:55.868+0300] {processor.py:157} INFO - Started process (PID=235881) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:49:55.903+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:49:55.913+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:49:55.912+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:49:55.961+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:49:55.957+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:49:55.962+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:49:55.961+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:49:55.963+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:49:56.093+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.248 seconds
[2023-08-15T21:50:27.694+0300] {processor.py:157} INFO - Started process (PID=236272) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:50:27.707+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:50:27.710+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:50:27.709+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:50:27.742+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:50:27.739+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:50:27.759+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:50:27.758+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:50:27.760+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:50:28.128+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.477 seconds
[2023-08-15T21:50:58.388+0300] {processor.py:157} INFO - Started process (PID=236676) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:50:58.394+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:50:58.397+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:50:58.396+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:50:58.420+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:50:58.414+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:50:58.421+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:50:58.420+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:50:58.422+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:50:58.676+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.302 seconds
[2023-08-15T21:51:29.041+0300] {processor.py:157} INFO - Started process (PID=237244) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:51:29.059+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:51:29.062+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:51:29.061+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:51:29.080+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:51:29.071+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:51:29.081+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:51:29.080+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:51:29.081+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:51:29.165+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.136 seconds
[2023-08-15T21:51:59.785+0300] {processor.py:157} INFO - Started process (PID=237786) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:51:59.795+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:51:59.808+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:51:59.807+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:51:59.822+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:51:59.820+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:51:59.823+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:51:59.822+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:51:59.823+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:51:59.910+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.137 seconds
[2023-08-15T21:52:30.400+0300] {processor.py:157} INFO - Started process (PID=238179) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:52:30.407+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:52:30.410+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:52:30.408+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:52:30.430+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:52:30.426+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:52:30.431+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:52:30.431+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:52:30.432+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:52:30.599+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.226 seconds
[2023-08-15T21:53:01.052+0300] {processor.py:157} INFO - Started process (PID=238547) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:53:01.055+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:53:01.057+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:53:01.056+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:53:01.070+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:53:01.067+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:53:01.071+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:53:01.070+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:53:01.071+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:53:01.156+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.118 seconds
[2023-08-15T21:53:31.719+0300] {processor.py:157} INFO - Started process (PID=239111) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:53:31.768+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:53:31.771+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:53:31.770+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:53:31.797+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:53:31.789+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:53:31.798+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:53:31.798+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:53:31.799+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:53:31.994+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.291 seconds
[2023-08-15T21:54:05.253+0300] {processor.py:157} INFO - Started process (PID=239697) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:54:05.282+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:54:05.309+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:54:05.284+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:54:05.336+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:54:05.334+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:54:05.337+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:54:05.337+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:54:05.357+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:54:05.698+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.463 seconds
[2023-08-15T21:54:36.678+0300] {processor.py:157} INFO - Started process (PID=240113) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:54:36.683+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:54:36.686+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:54:36.685+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:54:36.720+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:54:36.696+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:54:36.721+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:54:36.721+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:54:36.722+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:54:36.853+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.260 seconds
[2023-08-15T21:55:08.350+0300] {processor.py:157} INFO - Started process (PID=240525) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:55:08.372+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:55:08.375+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:55:08.374+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:55:08.412+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:55:08.393+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:55:08.414+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:55:08.413+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:55:08.415+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:55:08.642+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.308 seconds
[2023-08-15T21:55:38.889+0300] {processor.py:157} INFO - Started process (PID=240942) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:55:38.893+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:55:38.895+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:55:38.894+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:55:38.909+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:55:38.906+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:55:38.910+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:55:38.910+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:55:38.911+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:55:39.008+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.133 seconds
[2023-08-15T21:56:10.066+0300] {processor.py:157} INFO - Started process (PID=241510) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:56:10.078+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:56:10.081+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:56:10.080+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:56:10.094+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:56:10.091+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:56:10.095+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:56:10.095+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:56:10.096+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:56:10.210+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.158 seconds
[2023-08-15T21:56:42.057+0300] {processor.py:157} INFO - Started process (PID=242138) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:56:42.087+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:56:42.089+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:56:42.088+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:56:42.100+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:56:42.098+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:56:42.101+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:56:42.101+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:56:42.102+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:56:42.187+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.140 seconds
[2023-08-15T21:57:13.735+0300] {processor.py:157} INFO - Started process (PID=242610) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:57:13.738+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:57:13.740+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:57:13.739+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:57:13.753+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:57:13.750+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:57:13.754+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:57:13.754+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:57:13.755+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:57:13.851+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.130 seconds
[2023-08-15T21:57:44.544+0300] {processor.py:157} INFO - Started process (PID=243038) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:57:44.599+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:57:44.602+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:57:44.601+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:57:44.641+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:57:44.638+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:57:44.650+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:57:44.649+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:57:44.651+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:57:44.758+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.233 seconds
[2023-08-15T21:58:15.378+0300] {processor.py:157} INFO - Started process (PID=243469) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:58:15.383+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:58:15.386+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:58:15.384+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:58:15.399+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:58:15.396+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:58:15.400+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:58:15.399+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:58:15.401+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:58:15.478+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.115 seconds
[2023-08-15T21:58:46.681+0300] {processor.py:157} INFO - Started process (PID=244058) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:58:46.701+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:58:46.704+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:58:46.703+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:58:46.761+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:58:46.740+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:58:46.762+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:58:46.761+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:58:46.763+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:58:46.907+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.240 seconds
[2023-08-15T21:59:17.974+0300] {processor.py:157} INFO - Started process (PID=244567) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:59:17.989+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:59:17.992+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:59:17.991+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:59:18.016+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:59:18.005+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:59:18.017+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:59:18.017+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:59:18.018+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:59:18.124+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.169 seconds
[2023-08-15T21:59:49.411+0300] {processor.py:157} INFO - Started process (PID=244966) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:59:49.434+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:59:49.438+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:59:49.437+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:59:49.459+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:59:49.456+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:59:49.461+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:59:49.460+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:59:49.462+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:59:49.580+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.187 seconds
[2023-08-15T22:00:20.538+0300] {processor.py:157} INFO - Started process (PID=245351) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:00:20.541+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:00:20.544+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:00:20.543+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:00:20.558+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:00:20.555+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:00:20.559+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:00:20.559+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:00:20.560+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:00:20.676+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.155 seconds
[2023-08-15T22:00:51.907+0300] {processor.py:157} INFO - Started process (PID=245745) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:00:51.923+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:00:51.928+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:00:51.925+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:00:51.946+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:00:51.943+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:00:51.947+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:00:51.946+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:00:51.947+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:00:52.072+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.195 seconds
[2023-08-15T22:01:23.077+0300] {processor.py:157} INFO - Started process (PID=246318) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:01:23.079+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:01:23.082+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:01:23.081+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:01:23.092+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:01:23.090+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:01:23.093+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:01:23.093+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:01:23.094+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:01:23.167+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.101 seconds
[2023-08-15T22:01:54.733+0300] {processor.py:157} INFO - Started process (PID=246875) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:01:54.735+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:01:54.737+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:01:54.736+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:01:54.747+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:01:54.745+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:01:54.748+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:01:54.748+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:01:54.749+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:01:54.823+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.101 seconds
[2023-08-15T22:02:25.694+0300] {processor.py:157} INFO - Started process (PID=247258) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:02:25.696+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:02:25.699+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:02:25.698+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:02:25.712+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:02:25.709+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:02:25.713+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:02:25.713+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:02:25.714+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:02:25.795+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.116 seconds
[2023-08-15T22:02:56.744+0300] {processor.py:157} INFO - Started process (PID=247622) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:02:56.748+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:02:56.754+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:02:56.751+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:02:56.769+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:02:56.766+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:02:56.771+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:02:56.771+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:02:56.772+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:02:57.056+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.345 seconds
[2023-08-15T22:03:27.530+0300] {processor.py:157} INFO - Started process (PID=247958) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:03:27.539+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:03:27.542+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:03:27.541+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:03:27.555+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:03:27.552+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:03:27.556+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:03:27.556+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:03:27.557+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:03:27.651+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.136 seconds
[2023-08-15T22:03:57.961+0300] {processor.py:157} INFO - Started process (PID=248526) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:03:57.963+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:03:57.966+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:03:57.965+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:03:57.979+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:03:57.976+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:03:57.979+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:03:57.979+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:03:57.980+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:03:58.070+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.124 seconds
[2023-08-15T22:04:28.952+0300] {processor.py:157} INFO - Started process (PID=249077) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:04:28.955+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:04:28.957+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:04:28.956+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:04:28.968+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:04:28.966+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:04:28.969+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:04:28.968+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:04:28.970+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:04:29.040+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.104 seconds
[2023-08-15T22:05:00.045+0300] {processor.py:157} INFO - Started process (PID=249475) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:05:00.066+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:05:00.069+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:05:00.068+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:05:00.103+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:05:00.093+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:05:00.104+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:05:00.104+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:05:00.105+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:05:00.221+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.222 seconds
[2023-08-15T22:05:30.455+0300] {processor.py:157} INFO - Started process (PID=249865) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:05:30.457+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:05:30.459+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:05:30.459+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:05:30.470+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:05:30.468+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:05:30.471+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:05:30.471+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:05:30.472+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:05:30.542+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2023-08-15T22:06:01.463+0300] {processor.py:157} INFO - Started process (PID=250286) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:06:01.509+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:06:01.511+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:06:01.510+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:06:01.523+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:06:01.520+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:06:01.523+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:06:01.523+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:06:01.524+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:06:01.612+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.165 seconds
[2023-08-15T22:06:33.302+0300] {processor.py:157} INFO - Started process (PID=250866) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:06:33.417+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:06:33.419+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:06:33.418+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:06:33.427+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:06:33.425+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:06:33.428+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:06:33.427+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:06:33.428+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:06:33.502+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.211 seconds
[2023-08-15T22:07:04.598+0300] {processor.py:157} INFO - Started process (PID=251386) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:07:04.617+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:07:04.620+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:07:04.619+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:07:04.631+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:07:04.629+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:07:04.632+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:07:04.631+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:07:04.632+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:07:04.699+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.114 seconds
[2023-08-15T22:07:35.036+0300] {processor.py:157} INFO - Started process (PID=251762) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:07:35.037+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:07:35.039+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:07:35.038+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:07:35.047+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:07:35.045+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:07:35.047+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:07:35.047+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:07:35.047+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:07:35.095+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2023-08-15T22:08:06.693+0300] {processor.py:157} INFO - Started process (PID=252181) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:08:06.730+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:08:06.733+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:08:06.732+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:08:06.746+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:08:06.743+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:08:06.747+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:08:06.746+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:08:06.747+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:08:06.856+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.173 seconds
[2023-08-15T22:08:38.023+0300] {processor.py:157} INFO - Started process (PID=252721) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:08:38.187+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:08:38.190+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:08:38.189+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:08:38.202+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:08:38.200+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:08:38.203+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:08:38.203+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:08:38.204+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:08:38.431+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.520 seconds
[2023-08-15T22:09:08.588+0300] {processor.py:157} INFO - Started process (PID=253354) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:09:08.599+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:09:08.601+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:09:08.600+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:09:08.615+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:09:08.612+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:09:08.616+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:09:08.616+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:09:08.617+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:09:08.717+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.145 seconds
[2023-08-15T22:09:40.050+0300] {processor.py:157} INFO - Started process (PID=253736) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:09:40.053+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:09:40.056+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:09:40.055+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:09:40.075+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:09:40.068+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:09:40.076+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:09:40.076+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:09:40.077+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:09:40.194+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.158 seconds
[2023-08-15T22:10:11.926+0300] {processor.py:157} INFO - Started process (PID=254097) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:10:11.942+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:10:11.945+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:10:11.944+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:10:11.959+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:10:11.956+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:10:11.960+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:10:11.960+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:10:11.961+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:10:12.065+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.153 seconds
[2023-08-15T22:10:42.868+0300] {processor.py:157} INFO - Started process (PID=254455) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:10:42.871+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:10:42.873+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:10:42.872+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:10:42.891+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:10:42.886+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:10:42.892+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:10:42.892+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:10:42.893+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:10:43.000+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.148 seconds
[2023-08-15T22:11:14.124+0300] {processor.py:157} INFO - Started process (PID=255003) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:11:14.148+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:11:14.152+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:11:14.150+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:11:14.187+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:11:14.173+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:11:14.189+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:11:14.188+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:11:14.190+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:11:14.276+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.168 seconds
[2023-08-15T22:11:44.919+0300] {processor.py:157} INFO - Started process (PID=255575) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:11:44.922+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:11:44.925+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:11:44.924+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:11:44.936+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:11:44.934+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:11:44.937+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:11:44.937+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:11:44.938+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:11:45.015+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.109 seconds
[2023-08-15T22:12:15.952+0300] {processor.py:157} INFO - Started process (PID=255949) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:12:15.959+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:12:15.961+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:12:15.960+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:12:15.974+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:12:15.972+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:12:15.975+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:12:15.975+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:12:15.976+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:12:16.136+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.195 seconds
[2023-08-15T22:12:46.996+0300] {processor.py:157} INFO - Started process (PID=256333) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:12:46.999+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:12:47.001+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:12:47.000+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:12:47.012+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:12:47.010+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:12:47.013+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:12:47.013+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:12:47.014+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:12:47.084+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.101 seconds
[2023-08-15T22:13:17.442+0300] {processor.py:157} INFO - Started process (PID=256863) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:13:17.455+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:13:17.458+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:13:17.457+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:13:17.472+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:13:17.469+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:13:17.473+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:13:17.473+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:13:17.474+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:13:17.566+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.141 seconds
[2023-08-15T22:13:49.250+0300] {processor.py:157} INFO - Started process (PID=257465) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:13:49.269+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:13:49.271+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:13:49.270+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:13:49.283+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:13:49.281+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:13:49.284+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:13:49.284+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:13:49.285+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:13:49.412+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.185 seconds
[2023-08-15T22:14:20.305+0300] {processor.py:157} INFO - Started process (PID=257838) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:14:20.307+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:14:20.310+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:14:20.309+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:14:20.320+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:14:20.317+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:14:20.320+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:14:20.320+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:14:20.321+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:14:20.391+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.097 seconds
[2023-08-15T22:14:50.781+0300] {processor.py:157} INFO - Started process (PID=258217) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:14:50.799+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:14:50.802+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:14:50.801+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:14:50.826+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:14:50.823+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:14:50.827+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:14:50.827+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:14:50.828+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:14:50.969+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.203 seconds
[2023-08-15T22:15:21.127+0300] {processor.py:157} INFO - Started process (PID=258746) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:15:21.142+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:15:21.146+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:15:21.144+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:15:21.160+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:15:21.157+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:15:21.161+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:15:21.160+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:15:21.162+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:15:21.251+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.139 seconds
[2023-08-15T22:15:51.782+0300] {processor.py:157} INFO - Started process (PID=259328) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:15:51.804+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:15:51.807+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:15:51.805+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:15:51.832+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:15:51.829+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:15:51.833+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:15:51.832+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:15:51.834+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:15:51.959+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.202 seconds
[2023-08-15T22:16:22.842+0300] {processor.py:157} INFO - Started process (PID=259716) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:16:22.853+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:16:22.856+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:16:22.855+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:16:22.867+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:16:22.865+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:16:22.868+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:16:22.868+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:16:22.869+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:16:22.936+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.106 seconds
[2023-08-15T22:16:53.552+0300] {processor.py:157} INFO - Started process (PID=260114) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:16:53.554+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:16:53.556+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:16:53.555+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:16:53.567+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:16:53.565+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:16:53.568+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:16:53.568+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:16:53.569+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:16:53.657+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.117 seconds
[2023-08-15T22:17:25.236+0300] {processor.py:157} INFO - Started process (PID=260710) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:17:25.256+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:17:25.259+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:17:25.258+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:17:25.270+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:17:25.268+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:17:25.271+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:17:25.271+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:17:25.272+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:17:25.362+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.137 seconds
[2023-08-15T22:17:56.479+0300] {processor.py:157} INFO - Started process (PID=261273) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:17:56.488+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:17:56.491+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:17:56.490+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:17:56.510+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:17:56.507+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:17:56.510+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:17:56.510+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:17:56.511+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:17:56.603+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.136 seconds
[2023-08-15T22:18:27.378+0300] {processor.py:157} INFO - Started process (PID=261645) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:18:27.380+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:18:27.383+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:18:27.382+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:18:27.394+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:18:27.392+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:18:27.395+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:18:27.395+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:18:27.396+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:18:27.455+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.088 seconds
[2023-08-15T22:18:57.529+0300] {processor.py:157} INFO - Started process (PID=262031) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:18:57.539+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:18:57.541+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:18:57.540+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:18:57.553+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:18:57.550+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:18:57.554+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:18:57.553+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:18:57.555+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:18:57.625+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.108 seconds
[2023-08-15T22:19:28.779+0300] {processor.py:157} INFO - Started process (PID=262611) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:19:28.781+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:19:28.783+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:19:28.782+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:19:28.791+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:19:28.789+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:19:28.792+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:19:28.791+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:19:28.792+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:19:28.847+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.077 seconds
[2023-08-15T22:19:59.889+0300] {processor.py:157} INFO - Started process (PID=263155) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:19:59.892+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:19:59.895+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:19:59.894+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:19:59.907+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:19:59.905+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:19:59.908+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:19:59.908+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:19:59.909+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:19:59.995+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.120 seconds
[2023-08-15T22:20:31.495+0300] {processor.py:157} INFO - Started process (PID=263618) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:20:31.498+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:20:31.504+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:20:31.503+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:20:31.544+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:20:31.531+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:20:31.552+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:20:31.551+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:20:31.560+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:20:31.963+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.498 seconds
[2023-08-15T22:21:02.528+0300] {processor.py:157} INFO - Started process (PID=264324) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:21:02.547+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:21:02.549+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:21:02.548+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:21:02.562+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:21:02.559+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:21:02.563+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:21:02.563+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:21:02.564+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:21:02.678+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.188 seconds
[2023-08-15T22:21:32.829+0300] {processor.py:157} INFO - Started process (PID=264702) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:21:32.832+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:21:32.836+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:21:32.834+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:21:32.850+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:21:32.847+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:21:32.851+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:21:32.851+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:21:32.852+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:21:32.940+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.127 seconds
[2023-08-15T22:22:03.281+0300] {processor.py:157} INFO - Started process (PID=265391) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:22:03.283+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:22:03.286+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:22:03.285+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:22:03.298+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:22:03.296+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:22:03.299+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:22:03.299+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:22:03.300+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:22:03.372+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.103 seconds
[2023-08-15T22:22:33.913+0300] {processor.py:157} INFO - Started process (PID=265930) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:22:33.916+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:22:33.921+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:22:33.920+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:22:33.943+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:22:33.940+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:22:33.944+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:22:33.944+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:22:33.945+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:22:34.051+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.155 seconds
[2023-08-15T22:23:05.443+0300] {processor.py:157} INFO - Started process (PID=266331) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:23:05.460+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:23:05.462+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:23:05.461+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:23:05.472+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:23:05.470+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:23:05.473+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:23:05.472+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:23:05.473+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:23:05.550+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.117 seconds
[2023-08-15T22:23:36.301+0300] {processor.py:157} INFO - Started process (PID=266735) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:23:36.321+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:23:36.325+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:23:36.323+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:23:36.341+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:23:36.338+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:23:36.343+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:23:36.342+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:23:36.344+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:23:36.477+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.198 seconds
[2023-08-15T22:24:06.624+0300] {processor.py:157} INFO - Started process (PID=267275) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:24:06.639+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:24:06.641+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:24:06.640+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:24:06.651+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:24:06.649+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:24:06.652+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:24:06.651+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:24:06.652+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:24:06.728+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.114 seconds
[2023-08-15T22:24:37.457+0300] {processor.py:157} INFO - Started process (PID=267915) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:24:37.475+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:24:37.477+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:24:37.476+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:24:37.485+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:24:37.483+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:24:37.485+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:24:37.485+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:24:37.486+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:24:37.535+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.087 seconds
[2023-08-15T22:25:08.501+0300] {processor.py:157} INFO - Started process (PID=268310) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:25:08.503+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:25:08.505+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:25:08.504+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:25:08.516+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:25:08.513+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:25:08.516+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:25:08.516+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:25:08.517+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:25:08.591+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.102 seconds
[2023-08-15T22:25:39.255+0300] {processor.py:157} INFO - Started process (PID=268689) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:25:39.257+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:25:39.259+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:25:39.258+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:25:39.268+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:25:39.266+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:25:39.269+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:25:39.269+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:25:39.270+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:25:39.331+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.087 seconds
[2023-08-15T22:26:10.493+0300] {processor.py:157} INFO - Started process (PID=269266) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:26:10.495+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:26:10.498+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:26:10.496+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:26:10.509+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:26:10.506+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:26:10.510+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:26:10.509+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:26:10.510+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:26:10.573+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.093 seconds
[2023-08-15T22:26:41.031+0300] {processor.py:157} INFO - Started process (PID=269839) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:26:41.077+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T22:26:41.080+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:26:41.079+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:26:41.090+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:26:41.088+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T22:26:41.091+0300] {logging_mixin.py:150} INFO - [2023-08-15T22:26:41.091+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T22:26:41.092+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T22:26:41.177+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.164 seconds
