[2023-08-15T21:26:16.646+0300] {processor.py:157} INFO - Started process (PID=214944) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:26:16.649+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:26:16.652+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:26:16.651+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:26:16.699+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:26:16.684+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:26:16.700+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:26:16.699+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:26:16.700+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:26:16.749+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.126 seconds
[2023-08-15T21:29:36.148+0300] {processor.py:157} INFO - Started process (PID=217449) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:29:36.169+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:29:36.172+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:29:36.170+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:29:36.188+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:29:36.185+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:29:36.189+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:29:36.189+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:29:36.191+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:29:36.242+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.108 seconds
[2023-08-15T21:47:41.338+0300] {processor.py:157} INFO - Started process (PID=233839) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:47:41.374+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:47:41.376+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:47:41.375+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:47:41.387+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:47:41.385+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:47:41.388+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:47:41.388+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:47:41.389+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:47:41.477+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.153 seconds
[2023-08-15T21:48:12.617+0300] {processor.py:157} INFO - Started process (PID=234235) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:48:12.619+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:48:12.622+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:48:12.621+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:48:12.636+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:48:12.632+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:48:12.637+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:48:12.636+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:48:12.638+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:48:12.731+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.130 seconds
[2023-08-15T21:48:44.313+0300] {processor.py:157} INFO - Started process (PID=234857) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:48:44.329+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:48:44.331+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:48:44.330+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:48:44.385+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:48:44.382+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:48:44.385+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:48:44.385+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:48:44.388+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:48:44.700+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.425 seconds
[2023-08-15T21:49:23.542+0300] {processor.py:157} INFO - Started process (PID=235505) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:49:23.545+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:49:23.547+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:49:23.546+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:49:23.558+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:49:23.556+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:49:23.559+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:49:23.558+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:49:23.559+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:49:23.636+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.104 seconds
[2023-08-15T21:49:55.868+0300] {processor.py:157} INFO - Started process (PID=235881) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:49:55.903+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:49:55.913+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:49:55.912+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:49:55.961+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:49:55.957+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:49:55.962+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:49:55.961+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:49:55.963+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:49:56.093+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.248 seconds
[2023-08-15T21:50:27.694+0300] {processor.py:157} INFO - Started process (PID=236272) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:50:27.707+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:50:27.710+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:50:27.709+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:50:27.742+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:50:27.739+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:50:27.759+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:50:27.758+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:50:27.760+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:50:28.128+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.477 seconds
[2023-08-15T21:50:58.388+0300] {processor.py:157} INFO - Started process (PID=236676) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:50:58.394+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:50:58.397+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:50:58.396+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:50:58.420+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:50:58.414+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:50:58.421+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:50:58.420+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:50:58.422+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:50:58.676+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.302 seconds
[2023-08-15T21:51:29.041+0300] {processor.py:157} INFO - Started process (PID=237244) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:51:29.059+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:51:29.062+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:51:29.061+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:51:29.080+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:51:29.071+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:51:29.081+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:51:29.080+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:51:29.081+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:51:29.165+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.136 seconds
[2023-08-15T21:51:59.785+0300] {processor.py:157} INFO - Started process (PID=237786) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:51:59.795+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:51:59.808+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:51:59.807+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:51:59.822+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:51:59.820+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:51:59.823+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:51:59.822+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:51:59.823+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:51:59.910+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.137 seconds
[2023-08-15T21:52:30.400+0300] {processor.py:157} INFO - Started process (PID=238179) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:52:30.407+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:52:30.410+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:52:30.408+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:52:30.430+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:52:30.426+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:52:30.431+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:52:30.431+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:52:30.432+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:52:30.599+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.226 seconds
[2023-08-15T21:53:01.052+0300] {processor.py:157} INFO - Started process (PID=238547) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:53:01.055+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:53:01.057+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:53:01.056+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:53:01.070+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:53:01.067+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:53:01.071+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:53:01.070+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:53:01.071+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:53:01.156+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.118 seconds
[2023-08-15T21:53:31.719+0300] {processor.py:157} INFO - Started process (PID=239111) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:53:31.768+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:53:31.771+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:53:31.770+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:53:31.797+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:53:31.789+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:53:31.798+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:53:31.798+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:53:31.799+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:53:31.994+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.291 seconds
[2023-08-15T21:54:05.253+0300] {processor.py:157} INFO - Started process (PID=239697) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:54:05.282+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:54:05.309+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:54:05.284+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:54:05.336+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:54:05.334+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:54:05.337+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:54:05.337+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:54:05.357+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:54:05.698+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.463 seconds
[2023-08-15T21:54:36.678+0300] {processor.py:157} INFO - Started process (PID=240113) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:54:36.683+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:54:36.686+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:54:36.685+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:54:36.720+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:54:36.696+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:54:36.721+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:54:36.721+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:54:36.722+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:54:36.853+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.260 seconds
[2023-08-15T21:55:08.350+0300] {processor.py:157} INFO - Started process (PID=240525) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:55:08.372+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:55:08.375+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:55:08.374+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:55:08.412+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:55:08.393+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:55:08.414+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:55:08.413+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:55:08.415+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:55:08.642+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.308 seconds
[2023-08-15T21:55:38.889+0300] {processor.py:157} INFO - Started process (PID=240942) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:55:38.893+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:55:38.895+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:55:38.894+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:55:38.909+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:55:38.906+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:55:38.910+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:55:38.910+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:55:38.911+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:55:39.008+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.133 seconds
[2023-08-15T21:56:10.066+0300] {processor.py:157} INFO - Started process (PID=241510) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:56:10.078+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:56:10.081+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:56:10.080+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:56:10.094+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:56:10.091+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:56:10.095+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:56:10.095+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:56:10.096+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:56:10.210+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.158 seconds
[2023-08-15T21:56:42.057+0300] {processor.py:157} INFO - Started process (PID=242138) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:56:42.087+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:56:42.089+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:56:42.088+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:56:42.100+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:56:42.098+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:56:42.101+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:56:42.101+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:56:42.102+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:56:42.187+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.140 seconds
[2023-08-15T21:57:13.735+0300] {processor.py:157} INFO - Started process (PID=242610) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:57:13.738+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:57:13.740+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:57:13.739+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:57:13.753+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:57:13.750+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:57:13.754+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:57:13.754+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:57:13.755+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:57:13.851+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.130 seconds
[2023-08-15T21:57:44.544+0300] {processor.py:157} INFO - Started process (PID=243038) to work on /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:57:44.599+0300] {processor.py:826} INFO - Processing file /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2023-08-15T21:57:44.602+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:57:44.601+0300] {dagbag.py:541} INFO - Filling up the DagBag from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:57:44.641+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:57:44.638+0300] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2023-08-15T21:57:44.650+0300] {logging_mixin.py:150} INFO - [2023-08-15T21:57:44.649+0300] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2023-08-15T21:57:44.651+0300] {processor.py:838} WARNING - No viable dags retrieved from /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2023-08-15T21:57:44.758+0300] {processor.py:179} INFO - Processing /mnt/kali/DataHunt/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.233 seconds
